export const devcontainerFile = '.devcontainer/devcontainer.json'
export const devcontainerHashFile = '.devcontainer/.devcontainer-hash.txt'
export const name = 'devcontainer/spark'
export const pipelineFile = '.github/workflows/templates/container.template.yaml'
export const registry = 'REPLACE_WITH_YOUR_ACR_NAME.azurecr.io'